;; (add-to-list 'load-path "~/.emacs.d/elpa/benchmark-init-20220414.1612/")
;; (require 'benchmark-init)
;; ;; To disable collection of benchmark data after init is done.
;; (add-hook 'after-init-hook 'benchmark-init/deactivate)
(setq frame-resize-pixelwise t)
(set-frame-position (selected-frame) 0 0)
(set-frame-size (selected-frame) 2048 1200 t)
(setq default-frame-alist '((ns-transparent-titlebar . t)
			    (alpha-background . 80)
			    (width . 100)
			    (height . 40)))
