;;(setq package-enable-at-startup nil)
;; (add-to-list 'load-path "~/.emacs.d/elpa/benchmark-init-20220414.1612/")
;; (require 'benchmark-init)
;; ;; To disable collection of benchmark data after init is done.
;; (setq gcmh-dir "~/.emacs.d/elpa/gcmh-20201116.2251")
;; (when (file-exists-p gcmh-dir)
;;   (add-to-list 'load-path gcmh-dir)
;;   (require 'gcmh)
;;   (gcmh-mode 1))
(unless (bound-and-true-p my-computer-has-smaller-memory-p)
  (setq gc-cons-percentage 0.6)
  (setq gc-cons-threshold most-positive-fixnum))

(setq frame-resize-pixelwise t)
;; (set-frame-position (selected-frame) 0 0)
;; (set-frame-size (selected-frame) 2048 1200 t)
(setq default-frame-alist '((menu-bar-lines . 0)
                             (tool-bar-lines . 0)
                             (ns-transparent-titlebar . t)
                            (alpha-background . 90)
                            (width . 200)
                            (height . 60)))
