;; (ignore-errors (module-load (expand-file-name"~/.emacs.d/site-lisp/pop_select.dll")))
;; (pop-select/transparent-set-all-frame 235)
;; (setq find-program "c:/Users/zwxxm/scoop/apps/msys2/2023-03-18/usr/bin/find.exe")
;; (add-to-list 'exec-path "c:/Users/zwxxm/scoop/apps/msys2/2023-03-18/usr/bin/")
(add-to-list 'exec-path "/cygdrive/c/Users/Administrator/AppData/Local/Microsoft/WinGet/Links/")
(add-to-list 'exec-path "c:/Users/Administrator/AppData/Local/Microsoft/WinGet/Links/")
(provide 'init-win)
