(defun search-back ()
  (interactive)
  (let ((regex (read-string "Type: ")))
    (setq mycount 1)
    (while (< mycount 100)
      (telega-button-backward 1)
      (when (telega-msg-match-p (telega-msg-at) `(contains ,regex))
        (message "yes!")
	(telega-msg-at)
	)
      (setq mycount (1+ mycount))
      )))
